### ISSUE TITLE
Add feature to share the poll

### ISSUE THREAD

**Issue by TezBlocksBakery** [marigold-dev/tzvote#24]
Is it possible to add a share option for the poll that has been created? I created a poll and added all my delegators as eligible to vote on. But they have to go on the site and manually search for name of the poll which i don't think is very efficient especially if more bakers start using this to ask the same questions

**Comment by zamrokk** [comment]
@TezBlocksBakery 
I am refactoring the app and now on the url you can look at specific poll.

Btw, do you want also the `vote `button on the result/details page of a poll ?

![image](https://github.com/marigold-dev/tzvote/assets/2536368/285d1285-5660-4a9b-92bd-a4988b727bf8)

Right now, it is not, just on the search/list page

**Comment by zamrokk** [comment]
Maybe, you would like also to filter by `Creator `?

**Comment by TezBlocksBakery** [comment]
Hi Benjamin,

Yes, I believe having the vote button in the details page is more important.

Do you not think having all those different votes displayed a bit confusing?

And is it possible to create a link to a specific poll?

Kind regards,
Eli

________________________________

**Comment by TezBlocksBakery** [comment]
I don't believe that would be necessary.
Have you thought about an easy way to add a list of delegators?
________________________________

**Comment by zamrokk** [comment]
If you have an Android , you can already test a preview on ghostnet here : 

https://play.google.com/store/apps/details?id=dev.marigold.tzvote

**Comment by zamrokk** [comment]
Delegators : if you are baker, now you have a button to add all your delegators to the list of voters in 1 click

**Comment by zamrokk** [comment]
Link : I am working on this User Story next week, as each poll have specific URL now (no more SPA), so yes, you will be able to go on the result page or config page of each poll

**Comment by zamrokk** [comment]
I think I will rename the Settings to Details, like this we could manage + do other actions on this page

**Comment by zamrokk** [comment]
@TezBlocksBakery thank you for the feedback

**Comment by TezBlocksBakery** [comment]
Hi Benjamin,

I create polls, not with my baker wallet but with my payout wallet, could you add the option to pull delegators from any public baker?

Also i believe an option to hide polls by the poll creator would be a great addition incase a mistake has been made, i don't believe you can delete them if someone already has voted so hiding them would be the next best thing.

Maybe also hide finished polls from the main page after a week? So it doesn't get cluttered

Sorry for that i keep requesting stuff, i don't know how much work this is.
Thank you that you keep working on tzvote!

Kind regards,
Eli
________________________________

**Comment by zamrokk** [comment]
pull delegators from any public baker?    <= why others ? Why do you need this ? Because you don't connect with your baker directly ? Do you want to connect with a Ledger instead ?

**Comment by zamrokk** [comment]
_Also i believe an option to hide polls by the poll creator would be a great addition incase a mistake has been made, i don't believe you can delete them if someone already has voted so hiding them would be the next best thing._

<= A status to "REMOVE" or "DISABLED" , can be possible to filter out from indexer , yep ! Thx !!! Got it

**Comment by zamrokk** [comment]
_Maybe also hide finished polls from the main page after a week? So it doesn't get cluttered_

<= I can add an auto filter by end date time to last 15 days, why not

**Comment by zamrokk** [comment]
Just UI stuff is not a lot   ^o^

Smart contract is a bit more ..

**Comment by TezBlocksBakery** [comment]
Indeed, i don't connect with my baker directly, instead i use my payout wallet.
So, when i create a poll using my payout wallet, i need access to TEZ blocks delegators
________________________________

**Comment by zamrokk** [comment]
Thanks a lot @TezBlocksBakery I will all of this to next release (not sure yet about the `disabled `as it requires some redeployment of smart contracts :/)

**Comment by TezBlocksBakery** [comment]
Thank you Benjamin!
________________________________
