### ISSUE TITLE
bulk add voter addresses

### ISSUE THREAD

**Issue by webid** [marigold-dev/tzvote#38]
for Permissioned polls, would be very useful if the UI allowed us to add multiple addresses easily (csv file or any similar format pasted into a textarea)

**Comment by zamrokk** [comment]
A csv file where first column is a Tezos address
No need to separate with commas as there is only 1 column and x lines

**Comment by zamrokk** [comment]
@webid I release it this to ghostnet and mainnet right now, the apk will follow soon

**Comment by zamrokk** [comment]
released
